### ISSUE TITLE
Module/Electron issue

### ISSUE THREAD

**Issue by aakilfernandes** [ConsenSys/hooked-web3-provider#5]
By default, Electron exposes a global "module" object. This is still a browser environment, but hooked-web3-provider mistakes it for a node environment

https://github.com/ConsenSys/hooked-web3-provider/blob/master/build/hooked-web3-provider.js#L207-L210

**Comment by tcoulter** [comment]
@aakilfernandes Does Electron's `module` object have an `exports` property?

**Comment by aakilfernandes** [comment]
It does. However, I think I might of found an alternate solution.

Electron has a `node-integration` option, which can be set to false that removes the global `module`. My dapp doesn't need it, so it works for me.

I'll close for now, you can re-open if you think its the kind of thing that might come up again and you want to nip in the bud.
